# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_command.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61mera_command.proto\"q\n&pb_camera_management_request_reg_write\x12\x1e\n\x16i2c_peripheral_address\x18\x01 \x01(\x05\x12\x18\n\x10register_address\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"\xab\x01\n*pb_camera_management_request_sensor_select\x12R\n\rsensor_select\x18\x01 \x01(\x0e\x32;.pb_camera_management_request_sensor_select.sensor_select_e\")\n\x0fsensor_select_e\x12\n\n\x06HM01B0\x10\x00\x12\n\n\x06HM0360\x10\x01\"-\n+pb_camera_management_request_trigger_config\"\xf5\x01\n\x1cpb_camera_management_request\x12<\n\treg_write\x18\x01 \x01(\x0b\x32\'.pb_camera_management_request_reg_writeH\x00\x12\x44\n\rsensor_select\x18\x02 \x01(\x0b\x32+.pb_camera_management_request_sensor_selectH\x00\x12\x46\n\x0etrigger_config\x18\x03 \x01(\x0b\x32,.pb_camera_management_request_trigger_configH\x00\x42\t\n\x07request\"a\n\x1fpb_camera_read_request_set_crop\x12\x0f\n\x07start_x\x18\x01 \x01(\x05\x12\x0f\n\x07start_y\x18\x02 \x01(\x05\x12\r\n\x05len_x\x18\x03 \x01(\x05\x12\r\n\x05len_y\x18\x04 \x01(\x05\"2\n\"pb_camera_read_request_set_packing\x12\x0c\n\x04pack\x18\x01 \x01(\x08\"2\n\"pb_camera_read_request_dcmi_enable\x12\x0c\n\x04halt\x18\x01 \x01(\x08\"\xc4\x01\n\x16pb_camera_read_request\x12\x30\n\x04\x63rop\x18\x01 \x01(\x0b\x32 .pb_camera_read_request_set_cropH\x00\x12\x33\n\x04pack\x18\x02 \x01(\x0b\x32#.pb_camera_read_request_set_packingH\x00\x12\x38\n\tdcmi_halt\x18\x03 \x01(\x0b\x32#.pb_camera_read_request_dcmi_enableH\x00\x42\t\n\x07request\"\x8a\x01\n\x11pb_camera_request\x12:\n\x11\x63\x61mera_management\x18\x01 \x01(\x0b\x32\x1d.pb_camera_management_requestH\x00\x12.\n\x0b\x64\x63mi_config\x18\x02 \x01(\x0b\x32\x17.pb_camera_read_requestH\x00\x42\t\n\x07requestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_REG_WRITE']._serialized_start=24
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_REG_WRITE']._serialized_end=137
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_SENSOR_SELECT']._serialized_start=140
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_SENSOR_SELECT']._serialized_end=311
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_SENSOR_SELECT_SENSOR_SELECT_E']._serialized_start=270
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_SENSOR_SELECT_SENSOR_SELECT_E']._serialized_end=311
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_TRIGGER_CONFIG']._serialized_start=313
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST_TRIGGER_CONFIG']._serialized_end=358
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST']._serialized_start=361
  _globals['_PB_CAMERA_MANAGEMENT_REQUEST']._serialized_end=606
  _globals['_PB_CAMERA_READ_REQUEST_SET_CROP']._serialized_start=608
  _globals['_PB_CAMERA_READ_REQUEST_SET_CROP']._serialized_end=705
  _globals['_PB_CAMERA_READ_REQUEST_SET_PACKING']._serialized_start=707
  _globals['_PB_CAMERA_READ_REQUEST_SET_PACKING']._serialized_end=757
  _globals['_PB_CAMERA_READ_REQUEST_DCMI_ENABLE']._serialized_start=759
  _globals['_PB_CAMERA_READ_REQUEST_DCMI_ENABLE']._serialized_end=809
  _globals['_PB_CAMERA_READ_REQUEST']._serialized_start=812
  _globals['_PB_CAMERA_READ_REQUEST']._serialized_end=1008
  _globals['_PB_CAMERA_REQUEST']._serialized_start=1011
  _globals['_PB_CAMERA_REQUEST']._serialized_end=1149
# @@protoc_insertion_point(module_scope)
